service: shiptrack-logistics-saas
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.12  # Changed from python3.11 to match your local environment
  region: ap-south-1
  stage: ${opt:stage, 'dev'}
  timeout: 30  # Increased timeout for database connections
  memorySize: 512  # Increased memory for better performance
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    SECRET_KEY: ${env:SECRET_KEY}
    ALGORITHM: ${env:ALGORITHM, 'HS256'}
    ACCESS_TOKEN_EXPIRE_MINUTES: ${env:ACCESS_TOKEN_EXPIRE_MINUTES, '30'}
    CORS_ORIGINS: ${env:CORS_ORIGINS, '*'}

functions:
  api:
    handler: handler.handler
    timeout: 30
    memorySize: 512
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY
      - httpApi:
          path: /
          method: ANY

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
    strip: false
    pythonBin: python3.11  # Ensure consistent Python version
    pipCmdExtraArgs:
      - --no-cache-dir
    layer: false  # Include dependencies in the main package
